# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 789dae2f42c45ed88bcbc4ef1b4da960e717597a99e08332cdd7ddd0650b1b5e6ea7901be10f6460022eb0fc7d83dbdaf8d6da7022b390fa8621b97808c91374

test:
  secret_key_base: 3eadbb8880d26e11b7f25a5219250ae16873d51125e6afe3f3fc320ab960ba77686c898e6adfdae5bfc198ba6898706787dc84ce3f694420cafce601176ccd87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
